### PR TITLE
trimmed whitespace

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by Boddlnagg** [comment]
Thanks for the PR! Would you be able to resolve the conflicts, and see if new trailing whitespace has been introduced which should be fixed? I'd be willing to merge it then 👍

**Comment by kangalioo** [comment]
Rustfmt also removes redundant whitespace and might be a good idea to add anyways?

**Comment by Boddlnagg** [comment]
I explained my position regarding rustfmt here: https://github.com/Boddlnagg/midir/pull/79

Feel free to open a PR, but it should then also somehow be ensured (i.e. via CI) that rustfmt is being applied in the future.

**Comment by Boddlnagg** [comment]
Closing due to inactivity.

**Pull request closed without merging**
