### PR TITLE
Update windows crate to 0.37, remove memalloc dependency

### PR DESCRIPTION
**Pull request by hrydgard**
`PSTR` has moved to `core`, that's it.

Yes, the windows crate is [churning a bit much](https://github.com/microsoft/windows-rs/issues/1720), work is underway to make that better but for now, it's a quickly moving upgrade train...

### CODE REVIEW

**Comment by hrydgard** [comment]
I also went ahead and removed the "memalloc" crate dependency.

**Comment by Boddlnagg** [comment]
Thanks for the PR! I'm just not sure why you chose `16` for the alignment of the sysex_buffer? I thought it's just a byte buffer so there should be no special alignment requirements?

**Comment by hrydgard** [comment]
16 is a good "default" alignment and what you'll usually get in the end in practice, so I just put it in out of habit. It's true though that sysex command are byte streams so generally don't care about alignment. I can change it to 1 if you think that makes sense.

**Comment by Boddlnagg** [comment]
Thanks for the PR, and sorry that it took me so long to merge it.

**Comment by hrydgard** [comment]
Thanks, no problem!

All that's missing now is a new release :)

**Comment by hrydgard** [comment]
May I please request a new official release with this, so I can remove my forked repo? :)

**Comment by MarijnS95** [comment]
Note that `0.38` has been released in the meantime :)

**Comment by repi** [comment]
would it be possible to release a new version of this crate that includes these fixes?

**Pull request merged**
