### PR TITLE
fix build with pipewire-jack

### PR DESCRIPTION
**Pull request by Be-ing**
https://github.com/RustAudio/rust-jack/pull/154

### CODE REVIEW

**Comment by Boddlnagg** [comment]
Thank you! The update of the `jack-sys` version included in https://github.com/Boddlnagg/midir/pull/98 should make this PR unnecessary, but I'll leave it open until that PR is merged.

**Comment by Boddlnagg** [comment]
If you say that `jack-sys` version `0.2.3` is required, would #98 be sufficient? It upgrades to version `~0.2.1`, but that would be semver-compatible with version `0.2.3`, if I'm not mistaken. So you could get `midir` to use `0.2.3` by requiring `0.2.3` in your downstream crate.

I will still leave this issue open until the required version of `jack-sys` is `0.2.3` or later.

**Comment by Be-ing** [comment]
How about simply using `jack-sys = "0.2"` without specifying the patch version?

**Comment by Boddlnagg** [comment]
Yep, that's a good idea :-)

**Pull request merged**
