### PR TITLE
Update to 2021 edition/rustfmt

### PR DESCRIPTION
**Pull request by Jake-Shadle**
While starting on a completely different PR I quickly noticed my typical setup of running rustfmt on save was going to introduce a lot of churn in the PR so I'm opening this one first to see what your thoughts are, that way I can do the other PR without formatting/edition changes if this PR is not to your liking. I couldn't find any references to MSRV or edition in any previous PRs/issues/docs so AFAICT it's not been explicitly stated why this crate is using the default 2015 edition and not being formatted with rustfmt.

I can add a CI check for formatting if desired.

### CODE REVIEW

**Comment by Boddlnagg** [comment]
Thanks for the PR! I'm not opposed to this (actually I didn't even realize that it's still using the 2015 edition, and I have just never used rustfmt myself).
It will take a little more time for me to review this, though. Did you do the edition upgrade manually or automated?
And I assume rustfmt is just using the default configuration?

**Comment by Jake-Shadle** [comment]
I just ran `cargo fmt` then manually fixed up the few warnings emitted when using 2021 edition that weren't present in 2015. Everything is default.

**Comment by Jake-Shadle** [comment]
Oh and I should say this is stable (1.69) rustfmt.

**Comment by uklotzde** [comment]
I strongly recommend to use auto-formatting of code for any project with more than a single contributor! Otherwise you will constantly see lots of unrelated changes in untouched parts of the code.

 Ideally, the formatting is verified both locally and during CI, e.g. by using [pre-commit](https://pre-commit.com/).

@Jake-Shadle Please squash your commits and use meaningful commit messages that follow the recommended style, i.e. imperative verb and max. 52 characters.

**Comment by Boddlnagg** [comment]
Superseded by #134 and #135

**Pull request closed without merging**
