### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bgaster**
Old dependencies caused builds to fail, updated to latest for all platforms.

### CODE REVIEW

**Comment by Boddlnagg** [comment]
Thanks for the PR!

I'm not sure though in what situations builds would fail because of older versions? Especially semver-compatible updates like `libc` 0.2.21 to 0.2.74 should not be necessary, because the versions will be resolved by cargo in such a way that a common version is picked (the version `0.2.21` in `Cargo.toml` only says that this is the *minimal* version, any newer but semver-compatible version is also allowed).

Also, the CI failure shows that now the `nix` version conflicts with the version within `alsa`. Since `nix` is only used to handle error codes in `alsa`, it must always be compatible with the version of `nix` used by `alsa` internally (unfortunately `alsa` doesn't publicly reexport those types).

**Comment by bgaster** [comment]
THe problem is when compiling wasmer crate, for example, it depends on a different version of cookie store, which fails to build without the updated libc. I'm on Mac OS and so ALSA is not such an issue for me, but I understand that this is not a solution in general, in that case.

**Comment by Boddlnagg** [comment]
So can you update the PR to only contain the change that you actually need?

**Comment by Boddlnagg** [comment]
This has become stale. `libc` is the only dependency that's still older than the one proposed in the PR. If an update of that is important to you, please open a new PR.

**Pull request closed without merging**
